In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

csv_file_path = "C:\sample_py/vgsales.csv"
game = pd.read_csv(csv_file_path)
game.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [7]:
print('전체 데이터 건수 : ', len(game))

전체 데이터 건수 :  16598

In [8]:
print('컬럼별 결측치 개수')
len(game) - game.count()

컬럼별 결측치 개수

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [9]:
game.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
16593    False
16594    False
16595    False
16596    False
16597    False
Length: 16598, dtype: bool

In [10]:
game[game.duplicated()]

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

In [15]:
def outlier(df, col, z):
	return df[abs(df[col] - np.mean(df[col]))/np.std(df[col]) > z].index

def not_outlier(df, col, z):
	return df[abs(df[col] - np.mean(df[col]))/np.std(df[col]) <= z].index

In [12]:
game.loc[outlier(game, 'Global_Sales', 1.5)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
500,501,Call of Duty: Finest Hour,PS2,2004.0,Shooter,Activision,1.51,1.12,0.01,0.24,2.89
501,502,Zumba Fitness 2,Wii,2011.0,Sports,Majesco Entertainment,1.54,1.07,0.00,0.28,2.88
502,503,Syphon Filter,PS,1999.0,Shooter,Sony Computer Entertainment,2.03,0.72,0.02,0.11,2.88
503,504,Imagine: Babyz,DS,2007.0,Simulation,Ubisoft,1.30,1.27,0.00,0.31,2.88
504,505,Colin McRae Rally,PS,1998.0,Racing,Codemasters,0.09,2.43,0.12,0.22,2.87

In [13]:
game.loc[outlier(game, 'Global_Sales', 2)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
339,340,Tony Hawk's Pro Skater 4,PS2,2002.0,Sports,Activision,2.13,1.18,0.01,0.35,3.67
340,341,Midnight Club 3: DUB Edition,PSP,2005.0,Racing,Take-Two Interactive,1.65,1.22,0.00,0.79,3.66
341,342,Banjo-Kazooie,N64,1998.0,Platform,Nintendo,1.87,1.13,0.55,0.10,3.65
342,343,SOCOM: U.S. Navy SEALs,PS2,2002.0,Shooter,Sony Computer Entertainment,2.53,0.81,0.06,0.24,3.65
343,344,Guitar Hero: World Tour,Wii,2008.0,Misc,Activision,2.33,0.97,0.00,0.35,3.65

In [14]:
game.loc[outlier(game, 'Global_Sales', 3)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
176,177,Assassin's Creed II,X360,2009.0,Action,Ubisoft,3.10,1.56,0.08,0.51,5.27
177,178,Professor Layton and the Curious Village,DS,2007.0,Puzzle,Nintendo,1.22,2.48,1.03,0.52,5.26
178,179,Tomb Raider II,PS,1997.0,Action,Eidos Interactive,2.30,2.46,0.20,0.28,5.24
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
180,181,Dragon Quest VIII: Journey of the Cursed King,PS2,2004.0,Role-Playing,Square Enix,0.65,0.75,3.61,0.20,5.21

In [16]:
game.loc[not_outlier(game, 'Global_Sales', 1.5)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
505,506,Call of Duty: Ghosts,XOne,2013.0,Shooter,Activision,1.87,0.77,0.00,0.22,2.86
506,507,Madden NFL 13,X360,2012.0,Sports,Electronic Arts,2.53,0.16,0.00,0.17,2.86
507,508,The Elder Scrolls III: Morrowind,XB,2002.0,Role-Playing,Ubisoft,2.09,0.63,0.03,0.11,2.86
508,509,Mortal Kombat,PS3,2011.0,Fighting,Warner Bros. Interactive Entertainment,1.98,0.55,0.00,0.32,2.85
509,510,F-Zero,SNES,1990.0,Racing,Nintendo,1.37,0.51,0.89,0.07,2.85
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01